CrossSearchBayesianSkoptObject: Config 0 Exception. Config: {'ItemDotCF': 13} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 1 Exception. Config: {'ItemDotCF': 9} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 2 Exception. Config: {'ItemDotCF': 18} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 3 Exception. Config: {'ItemDotCF': 12} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 4 Exception. Config: {'ItemDotCF': 23} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 5 Exception. Config: {'ItemDotCF': 14} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 6 Exception. Config: {'ItemDotCF': 14} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 7 Exception. Config: {'ItemDotCF': 16} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 8 Exception. Config: {'ItemDotCF': 22} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 9 Exception. Config: {'ItemDotCF': 22} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 10 Exception. Config: {'ItemDotCF': 17} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 11 Exception. Config: {'ItemDotCF': 6} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 12 Exception. Config: {'ItemDotCF': 5} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 13 Exception. Config: {'ItemDotCF': 6} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 14 Exception. Config: {'ItemDotCF': 12} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 15 Exception. Config: {'ItemDotCF': 4} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 16 Exception. Config: {'ItemDotCF': 13} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 17 Exception. Config: {'ItemDotCF': 12} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 18 Exception. Config: {'ItemDotCF': 22} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 19 Exception. Config: {'ItemDotCF': 17} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 20 Exception. Config: {'ItemDotCF': 18} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 21 Exception. Config: {'ItemDotCF': 19} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 22 Exception. Config: {'ItemDotCF': 5} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 23 Exception. Config: {'ItemDotCF': 10} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 24 Exception. Config: {'ItemDotCF': 11} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 25 Exception. Config: {'ItemDotCF': 23} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 26 Exception. Config: {'ItemDotCF': 17} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 27 Exception. Config: {'ItemDotCF': 4} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 28 Exception. Config: {'ItemDotCF': 11} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 29 Exception. Config: {'ItemDotCF': 10} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 30 Exception. Config: {'ItemDotCF': 20} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 31 Exception. Config: {'ItemDotCF': 12} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 32 Exception. Config: {'ItemDotCF': 23} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 33 Exception. Config: {'ItemDotCF': 13} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 34 Exception. Config: {'ItemDotCF': 21} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 35 Exception. Config: {'ItemDotCF': 0} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 36 Exception. Config: {'ItemDotCF': 3} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 37 Exception. Config: {'ItemDotCF': 8} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 38 Exception. Config: {'ItemDotCF': 6} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 39 Exception. Config: {'ItemDotCF': 16} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 40 Exception. Config: {'ItemDotCF': 14} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 41 Exception. Config: {'ItemDotCF': 8} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 42 Exception. Config: {'ItemDotCF': 2} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 43 Exception. Config: {'ItemDotCF': 11} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 44 Exception. Config: {'ItemDotCF': 22} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 45 Exception. Config: {'ItemDotCF': 15} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 46 Exception. Config: {'ItemDotCF': 2} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 47 Exception. Config: {'ItemDotCF': 13} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 48 Exception. Config: {'ItemDotCF': 20} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 49 Exception. Config: {'ItemDotCF': 13} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 50 Exception. Config: {'ItemDotCF': 15} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 51 Exception. Config: {'ItemDotCF': 6} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 52 Exception. Config: {'ItemDotCF': 19} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 53 Exception. Config: {'ItemDotCF': 6} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 54 Exception. Config: {'ItemDotCF': 20} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 55 Exception. Config: {'ItemDotCF': 18} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 56 Exception. Config: {'ItemDotCF': 2} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 57 Exception. Config: {'ItemDotCF': 18} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 58 Exception. Config: {'ItemDotCF': 8} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 59 Exception. Config: {'ItemDotCF': 9} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 60 Exception. Config: {'ItemDotCF': 24} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 61 Exception. Config: {'ItemDotCF': 12} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 62 Exception. Config: {'ItemDotCF': 22} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 63 Exception. Config: {'ItemDotCF': 14} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 64 Exception. Config: {'ItemDotCF': 13} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 65 Exception. Config: {'ItemDotCF': 7} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 66 Exception. Config: {'ItemDotCF': 3} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 67 Exception. Config: {'ItemDotCF': 5} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 68 Exception. Config: {'ItemDotCF': 8} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 69 Exception. Config: {'ItemDotCF': 9} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 70 Exception. Config: {'ItemDotCF': 0} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 71 Exception. Config: {'ItemDotCF': 0} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 72 Exception. Config: {'ItemDotCF': 0} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

CrossSearchBayesianSkoptObject: Config 73 Exception. Config: {'ItemDotCF': 0} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 172, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 147, in _evaluate_on_validation
    self.recommender_input_args_list[i])
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\cross_validation\CrossSearchFixedObject.py", line 131, in _fit_model
    **current_fit_parameters)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 36, in fit
    weights = self.map_weights(weights)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridWeightedAverageRecommender.py", line 24, in map_weights
    new_w[rec] = self.mapping[w]
TypeError: 'NoneType' object is not subscriptable

