SearchBayesianSkoptObject: Config 0 Exception. Config: {'topK': 1730, 'alpha1': 0.8260031355266627, 'alpha2': 0.5123736414914168, 'alpha3': 0.8938848234178327, 'alpha4': 0.1854608871542132} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 1 Exception. Config: {'topK': 82, 'alpha1': 0.17427154864607255, 'alpha2': 0.6443791629157929, 'alpha3': 0.6505471151404467, 'alpha4': 0.3469458887109083} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 2 Exception. Config: {'topK': 1837, 'alpha1': 0.291331281579495, 'alpha2': 0.22612499082305476, 'alpha3': 0.4476473355516868, 'alpha4': 0.007878753838888699} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 3 Exception. Config: {'topK': 536, 'alpha1': 0.07332946963631261, 'alpha2': 0.8251738849291337, 'alpha3': 0.8331090909902942, 'alpha4': 0.33264342071545966} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 4 Exception. Config: {'topK': 1484, 'alpha1': 0.8624953530810902, 'alpha2': 0.5256721493805665, 'alpha3': 0.634798683345605, 'alpha4': 0.5508565019483944} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 5 Exception. Config: {'topK': 1627, 'alpha1': 0.7839584610454676, 'alpha2': 0.5230277904349834, 'alpha3': 0.6673907134146767, 'alpha4': 0.32219309055326034} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 6 Exception. Config: {'topK': 1504, 'alpha1': 0.11759291750973336, 'alpha2': 0.26381987885563013, 'alpha3': 0.6192185122194572, 'alpha4': 0.20121275084727314} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 7 Exception. Config: {'topK': 1544, 'alpha1': 0.2969523233671603, 'alpha2': 0.8347886881389431, 'alpha3': 0.46412362377452454, 'alpha4': 0.47341521818060495} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 8 Exception. Config: {'topK': 1774, 'alpha1': 0.10201574549367246, 'alpha2': 0.14688194967608473, 'alpha3': 0.11492768984502391, 'alpha4': 0.09850445097709984} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 9 Exception. Config: {'topK': 1069, 'alpha1': 0.5541147477589246, 'alpha2': 0.8600380218622746, 'alpha3': 0.7336776442004969, 'alpha4': 0.020481780623103355} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 10 Exception. Config: {'topK': 818, 'alpha1': 0.9695794324066521, 'alpha2': 0.28299525006777665, 'alpha3': 0.4020995704879643, 'alpha4': 0.02223146118114339} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 11 Exception. Config: {'topK': 1444, 'alpha1': 0.9494885164227354, 'alpha2': 0.3941301430248312, 'alpha3': 0.49269353403485705, 'alpha4': 0.3101751337688227} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 12 Exception. Config: {'topK': 607, 'alpha1': 0.2597823783782371, 'alpha2': 0.38647512874929, 'alpha3': 0.8642781410627522, 'alpha4': 0.9857587926662078} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 13 Exception. Config: {'topK': 1105, 'alpha1': 0.6285670719042091, 'alpha2': 0.4170713649288814, 'alpha3': 0.09753690676316198, 'alpha4': 0.3338183396155611} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 14 Exception. Config: {'topK': 216, 'alpha1': 0.2808071683078455, 'alpha2': 0.1250406587179739, 'alpha3': 0.8307882956705014, 'alpha4': 0.6080707973180807} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 15 Exception. Config: {'topK': 52, 'alpha1': 0.44595055788108817, 'alpha2': 0.9982916015942194, 'alpha3': 0.1609795195161581, 'alpha4': 0.18890519782582454} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 16 Exception. Config: {'topK': 1328, 'alpha1': 0.18104089368636958, 'alpha2': 0.8600565618875875, 'alpha3': 0.05366091456093526, 'alpha4': 0.27014031205936434} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 17 Exception. Config: {'topK': 1054, 'alpha1': 0.06701141645640053, 'alpha2': 0.9962138118873286, 'alpha3': 0.0551544946664423, 'alpha4': 0.9336165319287959} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 18 Exception. Config: {'topK': 549, 'alpha1': 0.3045872181321962, 'alpha2': 0.009602553508911817, 'alpha3': 0.6030347392063456, 'alpha4': 0.5536505579160862} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 19 Exception. Config: {'topK': 528, 'alpha1': 0.5808398191571256, 'alpha2': 0.13880286799072308, 'alpha3': 0.08014785210008026, 'alpha4': 0.8254354336690244} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 20 Exception. Config: {'topK': 1921, 'alpha1': 0.986708463298617, 'alpha2': 0.1033736353834446, 'alpha3': 0.9920099902039023, 'alpha4': 0.992255544841971} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 21 Exception. Config: {'topK': 140, 'alpha1': 0.9986479707632796, 'alpha2': 0.8045303086438462, 'alpha3': 0.984234709138553, 'alpha4': 0.9781160735181962} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 22 Exception. Config: {'topK': 1780, 'alpha1': 0.9683052841161914, 'alpha2': 0.9750375589869876, 'alpha3': 0.07248199936835244, 'alpha4': 0.9817060377584679} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 23 Exception. Config: {'topK': 1988, 'alpha1': 0.013291764869743265, 'alpha2': 0.015842539994293085, 'alpha3': 0.10324453123912516, 'alpha4': 0.9638525298663173} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 24 Exception. Config: {'topK': 58, 'alpha1': 0.9625693850122572, 'alpha2': 0.06642475559556006, 'alpha3': 0.0013663939608880018, 'alpha4': 0.8508038237043632} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 25 Exception. Config: {'topK': 49, 'alpha1': 0.039192773889492806, 'alpha2': 0.1181613668473095, 'alpha3': 0.01602333811298102, 'alpha4': 0.022656353518303193} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 26 Exception. Config: {'topK': 5, 'alpha1': 0.9971185470429597, 'alpha2': 0.9729339388487545, 'alpha3': 0.9517325460168506, 'alpha4': 0.048053945263767064} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 27 Exception. Config: {'topK': 89, 'alpha1': 0.03699715686083337, 'alpha2': 0.9429973241647421, 'alpha3': 0.986583416241654, 'alpha4': 0.9934006423912153} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 28 Exception. Config: {'topK': 62, 'alpha1': 0.9618449629979795, 'alpha2': 0.9828844647749295, 'alpha3': 0.002285632696559903, 'alpha4': 0.004168425734526361} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 29 Exception. Config: {'topK': 1996, 'alpha1': 0.18451553304271948, 'alpha2': 0.9351555802048487, 'alpha3': 0.9676087985044494, 'alpha4': 0.9471454085932522} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 30 Exception. Config: {'topK': 48, 'alpha1': 0.10026389643704375, 'alpha2': 0.019446380854560675, 'alpha3': 0.016696824110721452, 'alpha4': 0.9942808333179232} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

SearchBayesianSkoptObject: Config 31 Exception. Config: {'topK': 1885, 'alpha1': 0.9720982338795562, 'alpha2': 0.9309348413529565, 'alpha3': 0.02976609221355054, 'alpha4': 0.984317792447024} - Exception: Traceback (most recent call last):
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 191, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_parameters)
  File "/Users/tangtang.zhou/Documents/GitHubProjects/recsys_2019/src/tuning/SearchFixedObject.py", line 181, in _fit_model
    **current_fit_parameters)
TypeError: fit() got an unexpected keyword argument 'alpha4'

