SearchBayesianSkoptObject: Config 0 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 6, 'MIXED': 0.9887989995412185, 'SLIM_BPR': 0.5265931794527893, 'P3ALPHA': 0.677255184731409, 'RP3BETA': 0.02832798669564452, 'IALS': 0.47964825225936547, 'USER_ITEM_ALL': 0.1945664729029049} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 1 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 3, 'MIXED': 0.6352950037047577, 'SLIM_BPR': 0.30161977448713356, 'P3ALPHA': 0.9566024829847636, 'RP3BETA': 0.8456562310609506, 'IALS': 0.8150733787601612, 'USER_ITEM_ALL': 0.9062989651674185} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 2 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 2, 'MIXED': 0.4684883388357082, 'SLIM_BPR': 0.33148928623647916, 'P3ALPHA': 0.6042725597826866, 'RP3BETA': 0.8210829515034851, 'IALS': 0.1460518273640329, 'USER_ITEM_ALL': 0.15267696983222492} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 3 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.3022105585874167, 'SLIM_BPR': 0.23826804047383193, 'P3ALPHA': 0.20619376090217306, 'RP3BETA': 0.17942800135650808, 'IALS': 0.6147132515309935, 'USER_ITEM_ALL': 0.7384605311170928} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 4 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 9, 'MIXED': 0.2645544561437258, 'SLIM_BPR': 0.7845829779270806, 'P3ALPHA': 0.30336765336997257, 'RP3BETA': 0.5147801556621833, 'IALS': 0.6396943390361304, 'USER_ITEM_ALL': 0.7968228447223265} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 5 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 8, 'MIXED': 0.06869336947212196, 'SLIM_BPR': 0.035711146332562255, 'P3ALPHA': 0.07057723851588579, 'RP3BETA': 0.9296745309617699, 'IALS': 0.015553849131539083, 'USER_ITEM_ALL': 0.03589067468656662} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 6 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 9, 'MIXED': 0.8656997848206001, 'SLIM_BPR': 0.915976491299946, 'P3ALPHA': 0.05857171309050756, 'RP3BETA': 0.9147622527208688, 'IALS': 0.9510315757383563, 'USER_ITEM_ALL': 0.9659160670327861} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 7 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.002332950809743924, 'SLIM_BPR': 0.8573034351507665, 'P3ALPHA': 0.711220736363041, 'RP3BETA': 0.18384422369737427, 'IALS': 0.9847501548581772, 'USER_ITEM_ALL': 0.002368128940316272} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 8 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.944996776301506, 'SLIM_BPR': 0.7535814630186156, 'P3ALPHA': 0.47464242381256233, 'RP3BETA': 0.03264262278162025, 'IALS': 0.006735264242156026, 'USER_ITEM_ALL': 0.9805730176060514} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 9 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.7724308701096314, 'SLIM_BPR': 0.022871255088615254, 'P3ALPHA': 0.9061530451308077, 'RP3BETA': 0.07638193955985294, 'IALS': 0.9815358619523779, 'USER_ITEM_ALL': 0.83670844301515} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 10 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.04864591030643531, 'SLIM_BPR': 0.9909930290738459, 'P3ALPHA': 0.9243831071631895, 'RP3BETA': 0.9160944672479255, 'IALS': 0.9855732996032015, 'USER_ITEM_ALL': 0.08933140635109035} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 11 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.12022750650628891, 'SLIM_BPR': 0.9691129586269694, 'P3ALPHA': 0.9794326002143846, 'RP3BETA': 0.7886008117646777, 'IALS': 0.012420896666716755, 'USER_ITEM_ALL': 0.9620103687692129} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 12 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.948989733207049, 'SLIM_BPR': 0.03590041785617492, 'P3ALPHA': 0.03645799945637608, 'RP3BETA': 0.03931363022357876, 'IALS': 0.9871245489844921, 'USER_ITEM_ALL': 0.04131819255035013} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 13 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 2, 'MIXED': 0.9015091187773656, 'SLIM_BPR': 0.05780258994886468, 'P3ALPHA': 0.00459750215227417, 'RP3BETA': 0.922005385944658, 'IALS': 0.1174314855458897, 'USER_ITEM_ALL': 0.013122643715885566} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 14 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.024298050478153248, 'SLIM_BPR': 0.0636823868527574, 'P3ALPHA': 0.9798529069798059, 'RP3BETA': 0.14471177539220276, 'IALS': 0.07830955746625187, 'USER_ITEM_ALL': 0.10927736293923808} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 15 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.9798111146603057, 'SLIM_BPR': 0.6391222513086375, 'P3ALPHA': 1.0, 'RP3BETA': 0.9693837053017447, 'IALS': 0.033668722426571644, 'USER_ITEM_ALL': 0.024839667790489937} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 16 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.9791344602627524, 'SLIM_BPR': 0.9519326665255484, 'P3ALPHA': 0.003345300837457544, 'RP3BETA': 0.808035546594787, 'IALS': 0.9803731893199019, 'USER_ITEM_ALL': 0.980395139530885} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 17 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 3, 'MIXED': 0.010315298541656054, 'SLIM_BPR': 0.9647505782649406, 'P3ALPHA': 0.030554446102227732, 'RP3BETA': 0.9093400200024535, 'IALS': 0.040776866602561065, 'USER_ITEM_ALL': 0.921787631511855} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 18 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.6903032319009885, 'SLIM_BPR': 0.9794738712335878, 'P3ALPHA': 0.9757773725803407, 'RP3BETA': 0.0031156700715350835, 'IALS': 0.10999724888574834, 'USER_ITEM_ALL': 0.026267922512378847} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 19 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.35102372970960144, 'SLIM_BPR': 0.06964554555297144, 'P3ALPHA': 0.9879581672666783, 'RP3BETA': 0.905530428684319, 'IALS': 0.9937360152205873, 'USER_ITEM_ALL': 0.894633864684321} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 20 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.9518700864538844, 'SLIM_BPR': 0.8191767320212677, 'P3ALPHA': 0.05532334130579776, 'RP3BETA': 0.02780145791414624, 'IALS': 0.09865592640638957, 'USER_ITEM_ALL': 0.06982242774997684} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 21 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.024147426714559057, 'SLIM_BPR': 0.02098577119997436, 'P3ALPHA': 0.13213525577074672, 'RP3BETA': 0.8612723592757681, 'IALS': 0.041020625245085214, 'USER_ITEM_ALL': 0.940207125137478} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 22 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.20849185891844108, 'SLIM_BPR': 0.06431166024299849, 'P3ALPHA': 0.34917755572451037, 'RP3BETA': 0.019244058179898303, 'IALS': 0.033581368849299034, 'USER_ITEM_ALL': 0.9905696726425033} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 23 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.03728915226029728, 'SLIM_BPR': 0.044029156068236215, 'P3ALPHA': 0.04772165514131767, 'RP3BETA': 0.5031872206866308, 'IALS': 0.9440780962238591, 'USER_ITEM_ALL': 0.02977042418362664} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 24 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 2, 'MIXED': 0.9023732286983338, 'SLIM_BPR': 0.88499541654326, 'P3ALPHA': 0.015531639324331065, 'RP3BETA': 0.9359163367174258, 'IALS': 0.9414990252581567, 'USER_ITEM_ALL': 0.0027052031307410805} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 25 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.1456038935471418, 'SLIM_BPR': 0.9466933770199113, 'P3ALPHA': 0.17376640431500082, 'RP3BETA': 0.00014327638524247457, 'IALS': 0.9847999783605719, 'USER_ITEM_ALL': 0.8595415930828418} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 26 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.977515116763474, 'SLIM_BPR': 0.0036175347826307167, 'P3ALPHA': 0.8725994031189479, 'RP3BETA': 0.006226775736272396, 'IALS': 0.1322457656218963, 'USER_ITEM_ALL': 0.022618838441499926} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 27 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.8810299403122798, 'SLIM_BPR': 0.010837648676093943, 'P3ALPHA': 0.10934176249385982, 'RP3BETA': 0.0014123120848045594, 'IALS': 0.9370567663176215, 'USER_ITEM_ALL': 0.9533670802501473} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 28 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 9, 'MIXED': 0.9993721330472023, 'SLIM_BPR': 0.09052022333939548, 'P3ALPHA': 0.9123660181117774, 'RP3BETA': 0.9237955176369406, 'IALS': 0.14392698829188613, 'USER_ITEM_ALL': 0.9345543664288768} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 29 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 3, 'MIXED': 0.014542566968805883, 'SLIM_BPR': 0.9934396452890393, 'P3ALPHA': 0.945095634568891, 'RP3BETA': 0.18997199185668484, 'IALS': 0.9768786945298656, 'USER_ITEM_ALL': 0.012767238250544743} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 30 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 2, 'MIXED': 0.6387617763389922, 'SLIM_BPR': 0.9841849090938086, 'P3ALPHA': 0.026689168228336786, 'RP3BETA': 0.016550986886723854, 'IALS': 0.02520527640261972, 'USER_ITEM_ALL': 0.9619656944283367} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 31 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 10, 'MIXED': 0.9886544565056831, 'SLIM_BPR': 0.07179298397317858, 'P3ALPHA': 0.9731040390154442, 'RP3BETA': 0.9570655498841784, 'IALS': 0.9119931942740018, 'USER_ITEM_ALL': 0.057605307233944095} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 32 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 2, 'MIXED': 0.9916893747084312, 'SLIM_BPR': 0.9678388004679105, 'P3ALPHA': 0.10428501475552836, 'RP3BETA': 0.9908606960779643, 'IALS': 0.16753983111606718, 'USER_ITEM_ALL': 0.04296579385745072} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 33 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 1, 'MIXED': 0.01194689457319265, 'SLIM_BPR': 0.9998160171010756, 'P3ALPHA': 0.11642978838660248, 'RP3BETA': 0.9265159911076767, 'IALS': 0.8589933362269454, 'USER_ITEM_ALL': 0.0035012546048429636} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Config 34 Exception. Config: {'strategy': 'weighted_avg', 'multiplier_cutoff': 9, 'MIXED': 0.002801508547111587, 'SLIM_BPR': 0.8906025050678607, 'P3ALPHA': 0.9987100630817168, 'RP3BETA': 0.010553696752937604, 'IALS': 0.1054309515635862, 'USER_ITEM_ALL': 0.03357498374719848} - Exception: Traceback (most recent call last):
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 285, in _objective_function
    result_dict, result_string, recommender_instance, train_time, evaluation_time = self._evaluate_on_validation(current_fit_parameters_dict)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\tuning\SearchFixedObject.py", line 196, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 384, in evaluateRecommender
    self.usersToEvaluate)
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\course_lib\Base\Evaluation\Evaluator.py", line 278, in _run_evaluation_on_selected_users
    return_scores=True
  File "C:\Users\User.LAPTOP-FG37H74P\Documents\GitHub\recsys_2019\src\model\HybridRecommender\HybridRankBasedRecommender.py", line 164, in recommend
    rankings, scores = recommender_model.recommend(user_id_array, cutoff=cutoff_model,
AttributeError: 'dict' object has no attribute 'recommend'

SearchBayesianSkoptObject: Search complete. Best config is None: None
